"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const participant_1 = require("./participant");
exports.SIX_DECK_H17_DAS_NO_SURR = {
    HARD: {
        // Outside key is value of dealers upcard, ace == 11
        // Inside key is total value of players hand
        2: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.HIT,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.HIT,
            13: participant_1.Participant.actions.STAND,
            14: participant_1.Participant.actions.STAND,
            15: participant_1.Participant.actions.STAND,
            16: participant_1.Participant.actions.STAND,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        3: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.DOUBLE,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.HIT,
            13: participant_1.Participant.actions.STAND,
            14: participant_1.Participant.actions.STAND,
            15: participant_1.Participant.actions.STAND,
            16: participant_1.Participant.actions.STAND,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        4: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.DOUBLE,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.STAND,
            13: participant_1.Participant.actions.STAND,
            14: participant_1.Participant.actions.STAND,
            15: participant_1.Participant.actions.STAND,
            16: participant_1.Participant.actions.STAND,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        5: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.DOUBLE,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.STAND,
            13: participant_1.Participant.actions.STAND,
            14: participant_1.Participant.actions.STAND,
            15: participant_1.Participant.actions.STAND,
            16: participant_1.Participant.actions.STAND,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        6: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.DOUBLE,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.STAND,
            13: participant_1.Participant.actions.STAND,
            14: participant_1.Participant.actions.STAND,
            15: participant_1.Participant.actions.STAND,
            16: participant_1.Participant.actions.STAND,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        7: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.HIT,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.HIT,
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        8: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.HIT,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.HIT,
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        9: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.HIT,
            10: participant_1.Participant.actions.DOUBLE,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.HIT,
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        10: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.HIT,
            10: participant_1.Participant.actions.HIT,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.HIT,
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        11: {
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.HIT,
            9: participant_1.Participant.actions.HIT,
            10: participant_1.Participant.actions.HIT,
            11: participant_1.Participant.actions.DOUBLE,
            12: participant_1.Participant.actions.HIT,
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.STAND,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
    },
    PAIRS: {
        // Outside key is value of dealers upcard, ace == 11
        // Inside key value of one card in the pair, ace == 11
        2: {
            2: participant_1.Participant.actions.SPLIT,
            3: participant_1.Participant.actions.SPLIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.SPLIT,
            7: participant_1.Participant.actions.SPLIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.SPLIT,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        3: {
            2: participant_1.Participant.actions.SPLIT,
            3: participant_1.Participant.actions.SPLIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.SPLIT,
            7: participant_1.Participant.actions.SPLIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.SPLIT,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        4: {
            2: participant_1.Participant.actions.SPLIT,
            3: participant_1.Participant.actions.SPLIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.SPLIT,
            7: participant_1.Participant.actions.SPLIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.SPLIT,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        5: {
            2: participant_1.Participant.actions.SPLIT,
            3: participant_1.Participant.actions.SPLIT,
            4: participant_1.Participant.actions.SPLIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.SPLIT,
            7: participant_1.Participant.actions.SPLIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.SPLIT,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        6: {
            2: participant_1.Participant.actions.SPLIT,
            3: participant_1.Participant.actions.SPLIT,
            4: participant_1.Participant.actions.SPLIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.SPLIT,
            7: participant_1.Participant.actions.SPLIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.SPLIT,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        7: {
            2: participant_1.Participant.actions.SPLIT,
            3: participant_1.Participant.actions.SPLIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.SPLIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.STAND,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        8: {
            2: participant_1.Participant.actions.HIT,
            3: participant_1.Participant.actions.HIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.SPLIT,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        9: {
            2: participant_1.Participant.actions.HIT,
            3: participant_1.Participant.actions.HIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.DOUBLE,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.SPLIT,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        10: {
            2: participant_1.Participant.actions.HIT,
            3: participant_1.Participant.actions.HIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.STAND,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
        11: {
            2: participant_1.Participant.actions.HIT,
            3: participant_1.Participant.actions.HIT,
            4: participant_1.Participant.actions.HIT,
            5: participant_1.Participant.actions.HIT,
            6: participant_1.Participant.actions.HIT,
            7: participant_1.Participant.actions.HIT,
            8: participant_1.Participant.actions.SPLIT,
            9: participant_1.Participant.actions.STAND,
            10: participant_1.Participant.actions.STAND,
            11: participant_1.Participant.actions.SPLIT,
        },
    },
    SOFT: {
        // Outside key is value of dealers upcard, ace == 11
        // Inside key is total value of players hand, with ace == 11
        2: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.HIT,
            18: participant_1.Participant.actions.DS,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        3: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.DOUBLE,
            18: participant_1.Participant.actions.DS,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        4: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.DOUBLE,
            16: participant_1.Participant.actions.DOUBLE,
            17: participant_1.Participant.actions.DOUBLE,
            18: participant_1.Participant.actions.DS,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        5: {
            13: participant_1.Participant.actions.DOUBLE,
            14: participant_1.Participant.actions.DOUBLE,
            15: participant_1.Participant.actions.DOUBLE,
            16: participant_1.Participant.actions.DOUBLE,
            17: participant_1.Participant.actions.DOUBLE,
            18: participant_1.Participant.actions.DS,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        6: {
            13: participant_1.Participant.actions.DOUBLE,
            14: participant_1.Participant.actions.DOUBLE,
            15: participant_1.Participant.actions.DOUBLE,
            16: participant_1.Participant.actions.DOUBLE,
            17: participant_1.Participant.actions.DOUBLE,
            18: participant_1.Participant.actions.DS,
            19: participant_1.Participant.actions.DS,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        7: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.HIT,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        8: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.HIT,
            18: participant_1.Participant.actions.STAND,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        9: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.HIT,
            18: participant_1.Participant.actions.HIT,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        10: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.HIT,
            18: participant_1.Participant.actions.HIT,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
        11: {
            13: participant_1.Participant.actions.HIT,
            14: participant_1.Participant.actions.HIT,
            15: participant_1.Participant.actions.HIT,
            16: participant_1.Participant.actions.HIT,
            17: participant_1.Participant.actions.HIT,
            18: participant_1.Participant.actions.HIT,
            19: participant_1.Participant.actions.STAND,
            20: participant_1.Participant.actions.STAND,
            21: participant_1.Participant.actions.STAND,
        },
    },
};
